mysql:
  database: "database"
  name: "user"
  password: "password"
  host: "localhost"
  port: 3306


redis:
  host: "localhost"
  port: 6379
  password: "password"

app:
  gin_port: "8080"
  gin_log_file: "gin.log"
  web_mode: "gin"
  jwt_secret: "secret"
